#=====================================================
#   DIGITIZER (DETECTOR ELECTRONIC RESPONSE)
#          AND COINCIDENCES SORTER
#===================================================== 

# DIGITIZER

/gate/digitizer/Singles/insert adder
/gate/digitizer/Singles/insert readout
/gate/digitizer/Singles/readout/setDepth 1


### ENERGY BLURRING

#/gate/digitizer/Singles/insert blurring
#/gate/digitizer/Singles/blurring/setResolution 0.26
#/gate/digitizer/Singles/blurring/setResolution 0.
#/gate/digitizer/Singles/blurring/setEnergyOfReference 511. keV


### ENERGY CUT

/gate/digitizer/Singles/insert thresholder
/gate/digitizer/Singles/thresholder/setThreshold 150. keV
/gate/digitizer/Singles/insert upholder
/gate/digitizer/Singles/upholder/setUphold 350. keV


### DEAD TIME 

#/gate/digitizer/Singles/insert deadtime
#/gate/digitizer/Singles/deadtime/setDeadTime 300. ps
#/gate/digitizer/Singles/deadtime/setMode paralysable
#/gate/digitizer/Singles/deadtime/chooseDTVolume block


# COINCIDENCES SORTER 

/gate/digitizer/Coincidences/setWindow 350. ps
/gate/digitizer/Coincidences/setOffset 0. ps
/gate/digitizer/Coincidences/describe

#/gate/digitizer/name delay
#/gate/digitizer/insert coincidenceSorter
#/gate/digitizer/delay/setWindow 3500. ps
#/gate/digitizer/delay/setOffset 500. ns
#/gate/digitizer/delay/describe

#/gate/digitizer/name finalCoinc
#/gate/digitizer/insert coincidenceChain
#/gate/digitizer/finalCoinc/addInputName delay
#/gate/digitizer/finalCoinc/addInputName Coincidences
#/gate/digitizer/finalCoinc/usePriority true
#/gate/digitizer/finalCoinc/describe

/gate/output/root/enable
/gate/output/root/setFileName output/sensitivity_matrix
/gate/output/root/setRootSinglesAdderFlag 0
/gate/output/root/setRootSinglesReadoutFlag 0
/gate/output/root/setRootHitFlag 0
/gate/output/root/setRootSinglesFlag 1
/gate/output/root/setRootCoincidencesFlag 1

