# WORLD INITIALIZATION

/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1410. mm

# SCANNER

/gate/world/daughters/name scanner
/gate/world/daughters/insert cylinder
/gate/scanner/setMaterial Air
/gate/scanner/geometry/setRmin 411 mm
/gate/scanner/geometry/setRmax 477 mm
/gate/scanner/geometry/setHeight 912. mm
/gate/scanner/vis/forceWireframe
/gate/scanner/vis/setColor red

# FIRST MODULE WITH PLASTIC + SIPM + SHIELD

/gate/scanner/daughters/name module28
/gate/scanner/daughters/insert box
/gate/module28/placement/setTranslation 0.0 445.50 0.0 mm
/gate/module28/geometry/setXLength 96 mm
/gate/module28/geometry/setYLength 34 mm
/gate/module28/geometry/setZLength 912. mm
/gate/module28/setMaterial Air
/gate/module28/vis/forceWireframe 1
/gate/module28/vis/forceSolid 0
/gate/module28/vis/setColor blue

	
# SHIELD 1 THINK ABOUT THE ALU !!!!

/gate/module28/daughters/name shield1_28
/gate/module28/daughters/insert box
/gate/shield1_28/placement/setTranslation 0.0 0.0 342.0 mm
/gate/shield1_28/geometry/setXLength 96. mm
/gate/shield1_28/geometry/setYLength 34. mm
/gate/shield1_28/geometry/setZLength 228. mm
/gate/shield1_28/setMaterial Plastic
/gate/shield1_28/vis/forceWireframe
/gate/shield1_28/vis/setColor grey

/gate/shield1_28/daughters/name shield1_air28
/gate/shield1_28/daughters/insert box
/gate/shield1_air28/placement/setTranslation 0.0 0.0 0.0 mm
/gate/shield1_air28/geometry/setXLength 91. mm
/gate/shield1_air28/geometry/setYLength 24.5 mm
/gate/shield1_air28/geometry/setZLength 228. mm
/gate/shield1_air28/setMaterial Air
/gate/shield1_air28/vis/forceWireframe
/gate/shield1_air28/vis/setColor grey

# SHIELD 2 THINK ABOUT THE ALU !!!!
/gate/module28/daughters/name shield2_28
/gate/module28/daughters/insert box
/gate/shield2_28/placement/setTranslation 0.0 0.0 -342.0 mm
/gate/shield2_28/geometry/setXLength 96. mm
/gate/shield2_28/geometry/setYLength 34. mm
/gate/shield2_28/geometry/setZLength 228. mm
/gate/shield2_28/setMaterial Plastic
/gate/shield2_28/vis/forceWireframe
/gate/shield2_28/vis/setColor grey

/gate/shield2_28/daughters/name shield2_air28
/gate/shield2_28/daughters/insert box
/gate/shield2_air28/placement/setTranslation 0.0 0.0 0.0 mm
/gate/shield2_air28/geometry/setXLength 91. mm
/gate/shield2_air28/geometry/setYLength 24.5 mm
/gate/shield2_air28/geometry/setZLength 228. mm
/gate/shield2_air28/setMaterial Air
/gate/shield2_air28/vis/forceWireframe
/gate/shield2_air28/vis/setColor grey


# PLASTICS WITH WRAPPING + SIPM
# active_volume consists of two layers of wrapping, plastics and sipms

/gate/module28/daughters/name active_volume28
/gate/module28/daughters/insert box
/gate/active_volume28/placement/setTranslation 0.0 0.0 0.0 mm
/gate/active_volume28/geometry/setXLength 90.5 mm
/gate/active_volume28/geometry/setYLength 24.5 mm
/gate/active_volume28/geometry/setZLength 502. mm
/gate/active_volume28/setMaterial Air
/gate/active_volume28/vis/forceWireframe 0
/gate/active_volume28/vis/setColor magenta

#SiPM 1

/gate/active_volume28/daughters/name sipm1_28
/gate/active_volume28/daughters/insert box
/gate/sipm1_28/placement/setTranslation 0.0 0.0 250.5 mm
/gate/sipm1_28/geometry/setXLength 90 mm
/gate/sipm1_28/geometry/setYLength 24 mm
/gate/sipm1_28/geometry/setZLength 1. mm
/gate/sipm1_28/setMaterial Air
/gate/sipm1_28/vis/forceSolid
/gate/sipm1_28/vis/setColor red


#SiPM 2

/gate/active_volume28/daughters/name sipm2_28
/gate/active_volume28/daughters/insert box
/gate/sipm2_28/placement/setTranslation 0.0 0.0 -250.5 mm
/gate/sipm2_28/geometry/setXLength 90 mm
/gate/sipm2_28/geometry/setYLength 24 mm
/gate/sipm2_28/geometry/setZLength 1. mm
/gate/sipm2_28/setMaterial Air
/gate/sipm2_28/vis/forceSolid
/gate/sipm2_28/vis/setColor red


# ALL PANELs

/gate/active_volume28/daughters/name all_panels28
/gate/active_volume28/daughters/insert box
/gate/all_panels28/placement/setTranslation 0.0 0.0 0 mm
/gate/all_panels28/geometry/setXLength 90.5 mm
/gate/all_panels28/geometry/setYLength 24.5 mm
/gate/all_panels28/geometry/setZLength 500. mm
/gate/all_panels28/setMaterial Air
/gate/all_panels28/vis/forceWireframe 1
/gate/all_panels28/vis/setColor magenta


# SINGLE PANEL WITH WRAPPING (EXTERNAL LAYER)

/gate/all_panels28/daughters/name single_panel28
/gate/all_panels28/daughters/insert box
/gate/single_panel28/placement/setTranslation 0.0 0.0 0 mm
/gate/single_panel28/geometry/setXLength 6.2062 mm
/gate/single_panel28/geometry/setYLength 24.2062 mm
/gate/single_panel28/geometry/setZLength 500. mm
/gate/single_panel28/setMaterial Kapton
/gate/single_panel28/vis/forceWireframe 1
/gate/single_panel28/vis/setColor yellow


# INTERNAL LAYER IN SINGLE PANEL

/gate/single_panel28/daughters/name internal_layer28
/gate/single_panel28/daughters/insert box
/gate/internal_layer28/placement/setTranslation 0.0 0.0 0 mm
/gate/internal_layer28/geometry/setXLength 6.0762 mm
/gate/internal_layer28/geometry/setYLength 24.0762 mm
/gate/internal_layer28/geometry/setZLength 500. mm
# THE MATERIAL SHOULD BE THE VIKUITI FOIL - NOT ACHIEVABLE FOR US SO FAR
/gate/internal_layer28/setMaterial Air
/gate/internal_layer28/vis/forceWireframe 1
/gate/internal_layer28/vis/setColor yellow

# PLASTIC

/gate/internal_layer28/daughters/name plastic28
/gate/internal_layer28/daughters/insert box
/gate/plastic28/placement/setTranslation 0.0 0.0 0 mm
/gate/plastic28/geometry/setXLength 6 mm
/gate/plastic28/geometry/setYLength 24 mm
/gate/plastic28/geometry/setZLength 500. mm
/gate/plastic28/setMaterial EJ230
/gate/plastic28/vis/forceSolid
/gate/plastic28/vis/setColor white

# REPEATERS

# SINGLE_PANEL in ALL_PANELS
/gate/single_panel28/repeaters/insert cubicArray
/gate/single_panel28/cubicArray/setRepeatNumberX 13
/gate/single_panel28/cubicArray/setRepeatNumberY 1
/gate/single_panel28/cubicArray/setRepeatNumberZ 1
/gate/single_panel28/cubicArray/setRepeatVector 7. 0. 0. mm

# MODULE in the whole ring

/gate/module28/repeaters/insert ring
/gate/module28/ring/setRepeatNumber 28


# ATTACHEMENTS
/gate/systems/scanner/level1/attach module28
/gate/systems/scanner/level2/attach single_panel28
/gate/systems/scanner/level3/attach internal_layer28
/gate/systems/scanner/level4/attach plastic28


