# WORLD INITIALIZATION

/gate/world/geometry/setXLength 1100. mm
/gate/world/geometry/setYLength 1100. mm
/gate/world/geometry/setZLength 1500. mm
/gate/world/vis/forceWireframe 1
/gate/world/vis/forceSolid 0
/gate/world/vis/setColor black

# x-axis
#/gate/world/daughters/name xBox
#/gate/world/daughters/insert box
#/gate/xBox/vis/forceWireframe
#/gate/xBox/vis/setColor red
#/gate/xBox/geometry/setXLength 300 mm
#/gate/xBox/geometry/setYLength 0.1 mm
#/gate/xBox/geometry/setZLength 0.1 mm

# y-axis
#/gate/world/daughters/name yBox
#/gate/world/daughters/insert box
#/gate/yBox/vis/forceWireframe
#/gate/yBox/vis/setColor green
#/gate/yBox/geometry/setXLength 0.1 mm
#/gate/yBox/geometry/setYLength 300 mm
#/gate/yBox/geometry/setZLength 0.1 mm 

# z-axis
#/gate/world/daughters/name zBox
#/gate/world/daughters/insert box
#/gate/zBox/vis/forceWireframe
#/gate/zBox/vis/setColor blue
#/gate/zBox/geometry/setXLength 0.1 mm
#/gate/zBox/geometry/setYLength 0.1 mm
#/gate/zBox/geometry/setZLength 300 mm

# on translate legerement les axes pour les decaler par rapport à l'origine
#/gate/xBox/placement/setTranslation 50. 0.   0.   mm
#/gate/yBox/placement/setTranslation 0.   50. 0.   mm
#/gate/zBox/placement/setTranslation 0.   0.   100. mm


# SCANNER

/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/geometry/setRmin 369.61 mm
/gate/cylindricalPET/geometry/setRmax 440. mm
/gate/cylindricalPET/geometry/setHeight 500. mm
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white

# FIRST MODULE

/gate/cylindricalPET/daughters/name module1
/gate/cylindricalPET/daughters/insert box
/gate/module1/placement/setTranslation 381.86 0.0 0.0 mm
/gate/module1/geometry/setXLength 24. mm
/gate/module1/geometry/setYLength 96. mm
/gate/module1/geometry/setZLength 500. mm
/gate/module1/setMaterial Air
/gate/module1/vis/forceWireframe 1
/gate/module1/vis/forceSolid 0
/gate/module1/vis/setColor blue

# CRYSTAL (STRIP) MODULE

/gate/module1/daughters/name crystal1
/gate/module1/daughters/insert box
/gate/crystal1/placement/setTranslation 0.0 0.0 0.0 mm
/gate/crystal1/geometry/setXLength 24. mm
/gate/crystal1/geometry/setYLength 6. mm
/gate/crystal1/geometry/setZLength 500. mm
/gate/crystal1/setMaterial Air
/gate/crystal1/vis/forceWireframe 1
/gate/crystal1/vis/forceSolid 0
/gate/crystal1/vis/setColor white

# LAYER1 MODULE

/gate/crystal1/daughters/name layer_1
/gate/crystal1/daughters/insert box
/gate/layer_1/placement/setTranslation 0.0 0.0 0.0 mm
/gate/layer_1/geometry/setXLength 24. mm
/gate/layer_1/geometry/setYLength 6. mm
/gate/layer_1/geometry/setZLength 5. mm
/gate/layer_1/setMaterial EJ230
/gate/layer_1/vis/forceWireframe 1
/gate/layer_1/vis/forceSolid 0
/gate/layer_1/vis/setColor yellow

# LAYER1 REPEATER 

/gate/layer_1/repeaters/insert cubicArray
/gate/layer_1/cubicArray/setRepeatNumberX 1
/gate/layer_1/cubicArray/setRepeatNumberY 1
/gate/layer_1/cubicArray/setRepeatNumberZ 100
/gate/layer_1/cubicArray/setRepeatVector 0. 0. 5. mm

# CRYSTAL(STRIP) REPEATER 

/gate/crystal1/repeaters/insert cubicArray
/gate/crystal1/cubicArray/setRepeatNumberX 1
/gate/crystal1/cubicArray/setRepeatNumberY 13
/gate/crystal1/cubicArray/setRepeatNumberZ 1
/gate/crystal1/cubicArray/setRepeatVector 0. 7. 0. mm

# MODULE REPEATER 

/gate/module1/repeaters/insert ring
/gate/module1/ring/setRepeatNumber 24
/gate/module1/ring/enableAutoRotation

# SYSTEM

/gate/systems/cylindricalPET/rsector/attach module1
/gate/systems/cylindricalPET/crystal/attach crystal1
/gate/systems/cylindricalPET/layer0/attach layer_1

/gate/layer_1/attachCrystalSD


