# WORLD INITIALIZATION

/gate/world/geometry/setXLength 1000. mm
/gate/world/geometry/setYLength 1000. mm
/gate/world/geometry/setZLength 1410. mm

# SCANNER

/gate/world/daughters/name scanner
/gate/world/daughters/insert cylinder
/gate/scanner/setMaterial Air
/gate/scanner/geometry/setRmin 120. mm
/gate/scanner/geometry/setRmax 270. mm
/gate/scanner/geometry/setHeight 503. mm
/gate/scanner/vis/forceWireframe 0
/gate/scanner/vis/forceSolid 0
#/gate/scanner/vis/setColor red

# FIRST MODULE WITH PLASTIC + SIPM + SHIELD

/gate/scanner/daughters/name module10
/gate/scanner/daughters/insert box
/gate/module10/placement/setTranslation 0.0 159.11 0.0 mm
/gate/module10/geometry/setXLength 96 mm
/gate/module10/geometry/setYLength 34 mm
/gate/module10/geometry/setZLength 502. mm
/gate/module10/setMaterial Air
/gate/module10/vis/forceWireframe 0
/gate/module10/vis/forceSolid 0
#/gate/module10/vis/setColor blue

# FIRST MODULE WITH PLASTIC + SIPM + SHIELD

/gate/scanner/daughters/name module14
/gate/scanner/daughters/insert box
/gate/module14/placement/setTranslation 0.0 222.75 0.0 mm
/gate/module14/geometry/setXLength 96 mm
/gate/module14/geometry/setYLength 34 mm
/gate/module14/geometry/setZLength 502. mm
/gate/module14/setMaterial Air
/gate/module14/vis/forceWireframe 0
/gate/module14/vis/forceSolid 0
#/gate/module14/vis/setColor blue


# PLASTICS WITH WRAPPING + SIPM
# active_volume consists of two layers of wrapping, plastics and sipms

/gate/module10/daughters/name active_volume20
/gate/module10/daughters/insert box
/gate/active_volume20/placement/setTranslation 0.0 0.0 0.0 mm
/gate/active_volume20/geometry/setXLength 90.5 mm
/gate/active_volume20/geometry/setYLength 24.5 mm
/gate/active_volume20/geometry/setZLength 502. mm
/gate/active_volume20/setMaterial Air
/gate/active_volume20/vis/forceWireframe 0
/gate/active_volume20/vis/forceSolid 0
#/gate/active_volume20/vis/setColor magenta

#SiPM 1

/gate/active_volume20/daughters/name sipm1_20
/gate/active_volume20/daughters/insert box
/gate/sipm1_20/placement/setTranslation 0.0 0.0 250.5 mm
/gate/sipm1_20/geometry/setXLength 90 mm
/gate/sipm1_20/geometry/setYLength 24 mm
/gate/sipm1_20/geometry/setZLength 1. mm
/gate/sipm1_20/setMaterial Air
/gate/sipm1_20/vis/forceSolid
/gate/sipm1_20/vis/setColor red


#SiPM 2

/gate/active_volume20/daughters/name sipm2_20
/gate/active_volume20/daughters/insert box
/gate/sipm2_20/placement/setTranslation 0.0 0.0 -250.5 mm
/gate/sipm2_20/geometry/setXLength 90 mm
/gate/sipm2_20/geometry/setYLength 24 mm
/gate/sipm2_20/geometry/setZLength 1. mm
/gate/sipm2_20/setMaterial Air
/gate/sipm2_20/vis/forceSolid
/gate/sipm2_20/vis/setColor red

# PLASTICS WITH WRAPPING + SIPM
# active_volume consists of two layers of wrapping, plastics and sipms

/gate/module14/daughters/name active_volume28
/gate/module14/daughters/insert box
/gate/active_volume28/placement/setTranslation 0.0 0.0 0.0 mm
/gate/active_volume28/geometry/setXLength 90.5 mm
/gate/active_volume28/geometry/setYLength 24.5 mm
/gate/active_volume28/geometry/setZLength 502. mm
/gate/active_volume28/setMaterial Air
/gate/active_volume28/vis/forceWireframe 0
/gate/active_volume28/vis/forceSolid 0
#/gate/active_volume28/vis/setColor magenta

#SiPM 1

/gate/active_volume28/daughters/name sipm1_28
/gate/active_volume28/daughters/insert box
/gate/sipm1_28/placement/setTranslation 0.0 0.0 250.5 mm
/gate/sipm1_28/geometry/setXLength 90 mm
/gate/sipm1_28/geometry/setYLength 24 mm
/gate/sipm1_28/geometry/setZLength 1. mm
/gate/sipm1_28/setMaterial Air
/gate/sipm1_28/vis/forceSolid
/gate/sipm1_28/vis/setColor red


#SiPM 2

/gate/active_volume28/daughters/name sipm2_28
/gate/active_volume28/daughters/insert box
/gate/sipm2_28/placement/setTranslation 0.0 0.0 -250.5 mm
/gate/sipm2_28/geometry/setXLength 90 mm
/gate/sipm2_28/geometry/setYLength 24 mm
/gate/sipm2_28/geometry/setZLength 1. mm
/gate/sipm2_28/setMaterial Air
/gate/sipm2_28/vis/forceSolid
/gate/sipm2_28/vis/setColor red





# ALL PANELs

/gate/active_volume20/daughters/name all_panels20
/gate/active_volume20/daughters/insert box
/gate/all_panels20/placement/setTranslation 0.0 0.0 0 mm
/gate/all_panels20/geometry/setXLength 90.5 mm
/gate/all_panels20/geometry/setYLength 24.5 mm
/gate/all_panels20/geometry/setZLength 500. mm
/gate/all_panels20/setMaterial Air
/gate/all_panels20/vis/forceWireframe 0
/gate/all_panels20/vis/forceSolid 0
#/gate/all_panels20/vis/setColor magenta

# ALL PANELs

/gate/active_volume28/daughters/name all_panels28
/gate/active_volume28/daughters/insert box
/gate/all_panels28/placement/setTranslation 0.0 0.0 0 mm
/gate/all_panels28/geometry/setXLength 90.5 mm
/gate/all_panels28/geometry/setYLength 24.5 mm
/gate/all_panels28/geometry/setZLength 500. mm
/gate/all_panels28/setMaterial Air
/gate/all_panels28/vis/forceWireframe 0
/gate/all_panels28/vis/forceSolid 0
#/gate/all_panels28/vis/setColor magenta





# SINGLE PANEL WITH WRAPPING (EXTERNAL LAYER)

/gate/all_panels20/daughters/name single_panel20
/gate/all_panels20/daughters/insert box
/gate/single_panel20/placement/setTranslation 0.0 0.0 0 mm
/gate/single_panel20/geometry/setXLength 6.2062 mm
/gate/single_panel20/geometry/setYLength 24.2062 mm
/gate/single_panel20/geometry/setZLength 500. mm
/gate/single_panel20/setMaterial Kapton
/gate/single_panel20/vis/forceWireframe 0
/gate/single_panel20/vis/forceSolid 0
#/gate/single_panel20/vis/setColor yellow

# SINGLE PANEL WITH WRAPPING (EXTERNAL LAYER)

/gate/all_panels28/daughters/name single_panel28
/gate/all_panels28/daughters/insert box
/gate/single_panel28/placement/setTranslation 0.0 0.0 0 mm
/gate/single_panel28/geometry/setXLength 6.2062 mm
/gate/single_panel28/geometry/setYLength 24.2062 mm
/gate/single_panel28/geometry/setZLength 500. mm
/gate/single_panel28/setMaterial Kapton
/gate/single_panel28/vis/forceWireframe 0
/gate/single_panel28/vis/forceSolid 0
#/gate/single_panel28/vis/setColor yellow







# INTERNAL LAYER IN SINGLE PANEL

/gate/single_panel20/daughters/name internal_layer20
/gate/single_panel20/daughters/insert box
/gate/internal_layer20/placement/setTranslation 0.0 0.0 0 mm
/gate/internal_layer20/geometry/setXLength 6.0762 mm
/gate/internal_layer20/geometry/setYLength 24.0762 mm
/gate/internal_layer20/geometry/setZLength 500. mm
# THE MATERIAL SHOULD BE THE VIKUITI FOIL - NOT ACHIEVABLE FOR US SO FAR
/gate/internal_layer20/setMaterial Air
/gate/internal_layer20/vis/forceWireframe 0
/gate/internal_layer20/vis/forceSolid 0
#/gate/internal_layer20/vis/setColor white

# INTERNAL LAYER IN SINGLE PANEL

/gate/single_panel28/daughters/name internal_layer28
/gate/single_panel28/daughters/insert box
/gate/internal_layer28/placement/setTranslation 0.0 0.0 0 mm
/gate/internal_layer28/geometry/setXLength 6.0762 mm
/gate/internal_layer28/geometry/setYLength 24.0762 mm
/gate/internal_layer28/geometry/setZLength 500. mm
# THE MATERIAL SHOULD BE THE VIKUITI FOIL - NOT ACHIEVABLE FOR US SO FAR
/gate/internal_layer28/setMaterial Air
/gate/internal_layer28/vis/forceWireframe 0
/gate/internal_layer28/vis/forceSolid 0
#/gate/internal_layer28/vis/setColor white






# PLASTIC

/gate/internal_layer20/daughters/name plastic20
/gate/internal_layer20/daughters/insert box
/gate/plastic20/placement/setTranslation 0.0 0.0 0 mm
/gate/plastic20/geometry/setXLength 6 mm
/gate/plastic20/geometry/setYLength 24 mm
/gate/plastic20/geometry/setZLength 500. mm
/gate/plastic20/setMaterial EJ230
/gate/plastic20/vis/forceSolid
/gate/plastic20/vis/setColor yellow

# PLASTIC

/gate/internal_layer28/daughters/name plastic28
/gate/internal_layer28/daughters/insert box
/gate/plastic28/placement/setTranslation 0.0 0.0 0 mm
/gate/plastic28/geometry/setXLength 6 mm
/gate/plastic28/geometry/setYLength 24 mm
/gate/plastic28/geometry/setZLength 500. mm
/gate/plastic28/setMaterial EJ230
/gate/plastic28/vis/forceSolid
/gate/plastic28/vis/setColor yellow





# REPEATERS

# SINGLE_PANEL in ALL_PANELS
/gate/single_panel20/repeaters/insert cubicArray
/gate/single_panel20/cubicArray/setRepeatNumberX 13
/gate/single_panel20/cubicArray/setRepeatNumberY 1
/gate/single_panel20/cubicArray/setRepeatNumberZ 1
/gate/single_panel20/cubicArray/setRepeatVector 7. 0. 0. mm

# MODULE in the whole ring

/gate/module10/repeaters/insert ring
/gate/module10/ring/setRepeatNumber 10

# REPEATERS

# SINGLE_PANEL in ALL_PANELS
/gate/single_panel28/repeaters/insert cubicArray
/gate/single_panel28/cubicArray/setRepeatNumberX 13
/gate/single_panel28/cubicArray/setRepeatNumberY 1
/gate/single_panel28/cubicArray/setRepeatNumberZ 1
/gate/single_panel28/cubicArray/setRepeatVector 7. 0. 0. mm

# MODULE in the whole ring

/gate/module14/repeaters/insert ring
/gate/module14/ring/setRepeatNumber 14






# ATTACHEMENTS

#/gate/systems/scanner/level1/attach all_panels28
#/gate/systems/scanner/level2/attach single_panel28
#/gate/systems/scanner/level3/attach internal_layer28
#/gate/systems/scanner/level4/attach plastic28

# ATTACHEMENTS

#/gate/systems/scanner/level1/attach all_panels20
#/gate/systems/scanner/level2/attach single_panel20
#/gate/systems/scanner/level3/attach internal_layer20
#/gate/systems/scanner/level4/attach plastic20

